### ISSUE TITLE
Inspector JS is loaded into non-HTML files

### ISSUE THREAD

**Issue by msolnit** [querymetrics/boomerang-inspector#3]
Repro steps:

1. Install & enable the inspector extension.
2. Browse to http://www.lpcpeople.com/ical/rss/rss2.0.php?cal=&cpath=&rssview=day.
3. Observe extension JS code appended to the RSS XML.

I'm not sure if this is specific to RSS, to XML, or to any non-HTML, but either way, shouldn't happen :-).

![image](https://user-images.githubusercontent.com/1364430/82578777-b7612d00-9b41-11ea-8d3d-b3ec188efdb4.png)

**Comment by querymetrics** [comment]
@msolnit 
Fixed in https://github.com/querymetrics/boomerang-inspector/commit/6c33c26f0bc17ffd042b2fd8d7103970d6037106
We'll only inject in `text/html` pages
