### ISSUE TITLE
Could you provided some Pics / Screenshots

### ISSUE THREAD

**Issue by mc-chaos** [querymetrics/boomerang-inspector#8]
Please provide some screenshots to show the functions for this tool. I have no idea how/where to use this extension. I now the boomerang.js project, put what could i do with this tool?

**Comment by querymetrics** [comment]
Hi @mc-chaos , I added a couple screenshots to the README

**Comment by mc-chaos** [comment]
OK, THX that helps.

**Comment by mc-chaos** [comment]
Close
